    
 <div class="col-xs-12 col-sm-4  col-xs-offset-0 col-sm-offset-4 ">

  <!-- ///////////////////////////////////////////////////////////////////////////////////// -->
		codigos qr
		<div class="cerca">
			codigo de barras QR generado con la funcion js create_qrcode("123456");
			<div id="qr"></div>
			este codigo representa el txt 123456.
			<br><br>
			camara para la lectura del codigos QR scaner_qr('.xx');
			<div class="xx"></div>
		</div>









  <!-- ///////////////////////////////////////////////////////////////////////////////////// -->
		validador de campos de formularios¡¡¡
		<div class="cerca">
			
			jquery validation engine
			
			<form id="prueba" action="">
			<input id="prueba_campo" type="text" class="form-control" value="" >
			</form>
			<input type="button" id="validar" value="validar">




		</div> 










		





</div>