
  <!--==========================
    Home - inicio seccion
  ============================-->
  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

           <div class="carousel-item active">
            <div class="carousel-background"><img src="img/intro-carousel/6.jpg" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Bienvenidos a COTEDEM</h2>
                <p></p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/8.png" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Soporte y Mantenimiento Tecnológico</h2>
                <p>Brindamos servicios de soporte y mantenimiento, que van desde mantenimientos preventivos a la infraestructura tecnológica del cliente hasta mantenimientos correctivos con soporte en sitio según el acuerdo de niveles de servicio suscrito con el cliente.</p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/9.png" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Certificación Cableado Estructurado</h2>
                <p>La Certificación es un proceso de medición, mediante el cual se evalúa el desempeño de un sistema de Cableado Estructurado y se verifica el cumplimiento de los parámetros de transmisión especificados en las Normas que definen las categorías.</br>Los resultados de las pruebas son entregadas en medio digital e impreso, para que puedan ser analizadas y consultadas.</p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/1.jpg" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Consultoría Tecnológica</h2>
                <p>CODETEM ofrece al servicio del cliente consultoría tecnológica de calidad gracias a su experiencia y conocimiento en proyectos de infraestructuras y sistemas de información y comunicación. </br> Optimice el valor de sus inversiones en el área tecnológica y personalice su infraestructura de una forma eficiente, rentable y ampliable al contratar nuestros servicios de Asesoría Tecnológica.</p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/4.jpg" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Soluciones de Videovigilancia</h2>
                <p>En CODETEM contamos con sistemas que se ajustan a diversas necesidades. Todas las soluciones de videovigilancia pueden ser monitoreadas desde una PC o dispositivo móvil. Capaces de mostrar imágenes de alta calidad, facilitando el control y vigilancia, de forma económica y confiable.  </br>Todas las soluciones cuentan con grabación y almacenamiento de videos.</p>
                
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="img/intro-carousel/7.png" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>Soluciones Wi-Fi</h2>
                <p> En CODETEM nos especializamos en implementar infraestructuras de conectividad WIFI a todo tipo de empresas, con equipamientos líder en soluciones WiFi capaces de soportar aplicaciones de datos, voz y video. </br> Nuestras soluciones WiFi incluyen enlaces inalámbricos, siempre con el objetivo de anular las distancias en las comunicaciones entre diferentes localizaciones, usuarios y/o dispositivos, y de más rápida instalación que las infraestructuras cableadas. </p>
                
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Anterior</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Siguiente</span>
        </a>

      </div>
    </div>
  </section><!-- #intro -->

  <main id="main">

    <!--==========================
      algunos servicios seccion
    ============================-->
    <!-- <section id="featured-services">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 box">
            <i class="ion-ios-bookmarks-outline"></i>
            <h4 class="title"><a href="">Lorem Ipsum Delino</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
          </div>

          <div class="col-lg-4 box box-bg">
            <i class="ion-ios-stopwatch-outline"></i>
            <h4 class="title"><a href="">Dolor Sitema</a></h4>
            <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
          </div>

          <div class="col-lg-4 box">
            <i class="ion-ios-heart-outline"></i>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
          </div>

        </div>
      </div>
    </section> --><!-- #featured-services -->

    <!--==========================
      Nosotros Seccion
    ============================-->
    <section id="about">
      <div class="container">

        <header class="section-header">
          <h3>Nosotros</h3>
          <p><?php echo $this->nosotros["parrafo1"]; ?></p>
          <p><?php echo $this->nosotros["parrafo2"]; ?></p>
          <P><?php echo $this->nosotros["parrafo3"]; ?></P>
          <p><?php echo $this->nosotros["parrafo4"]; ?></p>
          <p><?php echo $this->nosotros["parrafo5"]; ?></p>
          <center> <h4 class="nosotros">En COTEDEM queremos potenciar su crecimiento. Y lo más importante: </br>
<b>¡Sabemos cómo hacerlo!</b></h4> </center>
        </header>

        <div class="row about-cols">
          <div class="col-md-6  wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="img/about-mission.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Nuestra Misión</a></h2>
              <p>
                <?php echo $this->informacion["mision"]; ?>
              </p> &nbsp;</br>
            </div>
          </div><!-- <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col">
              <div class="img">
                <img src="img/about-plan.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-list-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Nuestro Plan</a></h2>
              <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem  doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
              </p> &nbsp;</br> &nbsp;</br>
            </div>
          </div> -->

          <div class="col-md-6 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col">
              <div class="img">
                <img src="img/about-vision.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-eye-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Nuestra Visión</a></h2>
              <p>
                <?php echo $this->informacion["vision"]; ?>
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- #about -->

    <!--==========================
      Seccion de Servicios
    ============================-->
    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Servicios</h3>
          <p>En COTEDEM, Ofrecemos una gran variedad de servicios que pueden ser de gran ayuda y/o utilidad para su empresa. Somos expertos en brindar soluciones tecnológicas. Algunos de nuestros servicios son:</p>
        </header>

        <div class="row">

          <?php 
      for ($i=0; $i < count($this->servicios) ; $i++) { ?>

        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-analytics-outline"></i></div>
            <h4 class="title"><a href="javascript:null()"><?php echo $this->servicios[$i]["titulo"] ?></a></h4>
            <p class="description"><?php echo $this->servicios[$i]["descripcion"] ?></p>
          </div>

    <?php     
      }
     ?>

          
          
          
        </div>

      </div>
    </section><!-- #services -->
<!-- 
    ==========================
      Call To Action Section
    ============================
    <section id="call-to-action" class="wow fadeIn">
      <div class="container text-center">
        <h3>Call To Action</h3>
        <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a class="cta-btn" href="#">Call To Action</a>
      </div>
    </section> #call-to-action

    ==========================
      Skills Section
    ============================
    <section id="skills">
      <div class="container">

        <header class="section-header">
          <h3>Our Skills</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
        </header>

        <div class="skills-content">

          <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
              <span class="skill">HTML <i class="val">100%</i></span>
            </div>
          </div>

          <div class="progress">
            <div class="progress-bar bg-info" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
              <span class="skill">CSS <i class="val">90%</i></span>
            </div>
          </div>

          <div class="progress">
            <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
              <span class="skill">JavaScript <i class="val">75%</i></span>
            </div>
          </div>

          <div class="progress">
            <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">
              <span class="skill">Photoshop <i class="val">55%</i></span>
            </div>
          </div>

        </div>

      </div>
    </section>

    ==========================
      Facts Section
    ============================
    <section id="facts"  class="wow fadeIn">
      <div class="container">

        <header class="section-header">
          <h3>Facts</h3>
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </header>

        <div class="row counters">

  				<div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">274</span>
            <p>Clients</p>
  				</div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">421</span>
            <p>Projects</p>
  				</div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">1,364</span>
            <p>Hours Of Support</p>
  				</div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">18</span>
            <p>Hard Workers</p>
  				</div>

  			</div>

        <div class="facts-img">
          <img src="img/facts-img.png" alt="" class="img-fluid">
        </div>

      </div>
    </section>#facts -->

    <!--==========================
      Portfolio Section
    ============================-->
    <!-- <section id="portfolio"  class="section-bg" >
      <div class="container">

        <header class="section-header">
          <h3 class="section-title">Portfolio</h3>
        </header>

        <div class="row">
          <div class="col-lg-12">
            <ul id="portfolio-flters">
              <li data-filter="*" class="filter-active">All</li>
              <li data-filter=".filter-app">App</li>
              <li data-filter=".filter-card">Card</li>
              <li data-filter=".filter-web">Web</li>
            </ul>
          </div>
        </div>

        <div class="row portfolio-container">

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/app1.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/app1.jpg" data-lightbox="portfolio" data-title="App 1" class="link-preview" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">App 1</a></h4>
                <p>App</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/web3.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/web3.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Web 3</a></h4>
                <p>Web</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/app2.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/app2.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">App 2</a></h4>
                <p>App</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/card2.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/card2.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Card 2</a></h4>
                <p>Card</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/web2.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/web2.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 2" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Web 2</a></h4>
                <p>Web</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/app3.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/app3.jpg" class="link-preview" data-lightbox="portfolio" data-title="App 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">App 3</a></h4>
                <p>App</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/card1.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/card1.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Card 1</a></h4>
                <p>Card</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/card3.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/card3.jpg" class="link-preview" data-lightbox="portfolio" data-title="Card 3" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Card 3</a></h4>
                <p>Card</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
            <div class="portfolio-wrap">
              <figure>
                <img src="img/portfolio/web1.jpg" class="img-fluid" alt="">
                <a href="img/portfolio/web1.jpg" class="link-preview" data-lightbox="portfolio" data-title="Web 1" title="Preview"><i class="ion ion-eye"></i></a>
                <a href="#" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
              </figure>

              <div class="portfolio-info">
                <h4><a href="#">Web 1</a></h4>
                <p>Web</p>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section> --><!-- #portfolio -->

    <!--==========================
      Clients Section
    ============================-->
      <section id="clientes" class="wow fadeInUp">
      <div class="container">

        <header class="section-header">
          <h3>Clientes</h3>
          <p>Clientes que han confiado en nuestro servicio:</p>
        </header>

        <div class="owl-carousel clients-carousel">
          <a href="https://www.ant.gob.ec/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/1.png" alt=""></a>
          <a href="http://www.bmi.com.ec/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/2.png" alt=""></a>
          <a href="https://drcarlos-montenegro.com/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/3.png" alt=""></a>
          <a href="http://www.edimca.com.ec/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/4.png" alt=""></a>
          <a href="http://www.fideval.com/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/5.png" alt=""></a>
          <a href="http://www.gloapsa.com" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/6.png" alt=""></a>
          <a href="http://www.grupofarmadelecuador.com/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/7.png" alt=""></a>
          <a href="https://consumer.huawei.com/latin/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/8.png" alt=""></a>
        </div>


        <div class="owl-carousel clients-carousel">
          <a href="https://www.iess.gob.ec/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/9.png" alt="">
          <a href="https://www.ingelcom.net/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/10.png" alt=""> </a>
          <a href="https://www.foxtv.es/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/11.png" alt=""></a>
          <a href="https://www.lexvalor.com/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/12.png" alt=""></a>
          <a href="https://www.espanol.marriott.com/default.mi" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/13.png" alt=""></a>
          <a href="http://www.terrazos.com.ec/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/14.png" alt=""></a>
          <a href="http://www.uta.edu.ec" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/15.png" alt=""></a>
          <a href="http://www.yepezvaca.com/" target="_blank"><img src="<?php echo BASE_URL; ?>img/clientes/16.png" alt=""></a>
        </div>

      </div>
    </section><!-- #clients -->

    <section id="marcas" class="wow fadeInUp">
      <div class="container">

        <header class="section-header">
          <h3>Marcas</h3>
          <p>En <b>COTEDEM</b>, Ofrecemos las siguientes marcas:</p>
        </header>

        <div class="owl-carousel clients-carousel">
          <img src="img/marcas/marcas-1.png" alt="">
          <img src="img/marcas/marcas-2.png" alt="">
          <img src="img/marcas/marcas-3.png" alt="">
          <img src="img/marcas/marcas-4.png" alt="">
          <img src="img/marcas/marcas-5.png" alt="">
          <img src="img/marcas/marcas-6.png" alt="">
          <img src="img/marcas/marcas-7.png" alt="">
          <img src="img/marcas/marcas-8.png" alt="">
          <!-- <img src="img/marcas/marcas-9.png" alt=""> -->
          <img src="img/marcas/marcas-10.png" alt="">
          <img src="img/marcas/marcas-11.png" alt="">
          <img src="img/marcas/marcas-12.png" alt="">
          <img src="img/marcas/marcas-13.png" alt="">
          <img src="img/marcas/marcas-14.png" alt="">
          <!-- <img src="img/marcas/marcas-15.png" alt=""> -->
          <img src="img/marcas/marcas-16.png" alt="">
          <!-- <img src="img/marcas/marcas-17.png" alt=""> -->
        </div>


        <div class="owl-carousel clients-carousel">
           <img src="img/marcas/marcas-18.png" alt="">
          <!-- <img src="img/marcas/marcas-19.png" alt=""> -->
          <img src="img/marcas/marcas-20.png" alt="">
          <img src="img/marcas/marcas-21.png" alt="">
          <img src="img/marcas/marcas-22.png" alt="">
          <img src="img/marcas/marcas-23.png" alt="">
          <img src="img/marcas/marcas-24.png" alt="">
          <img src="img/marcas/marcas-26.png" alt="">
          <img src="img/marcas/marcas-27.png" alt="">
          <img src="img/marcas/marcas-28.png" alt="">
          <img src="img/marcas/marcas-29.png" alt="">
          <img src="img/marcas/marcas-30.png" alt="">
          <img src="img/marcas/marcas-31.png" alt="">
          <img src="img/marcas/marcas-32.png" alt="">
          <img src="img/marcas/marcas-33.png" alt="">
        </div>


      </div>
    </section><!-- #clients -->

    
<section id="ubicacion" class="wow fadeInUp">
  <header class="section-header">
          <h3>Nuestra Ubicación</h3>
          
        </header>
  <center>
   <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1994.9041614852215!2d-78.4887515!3d-0.1282638!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91d585429e5256f1%3A0xb1e2d10f64c52a8b!2sLuis+Tufino+Y+Sancho+Ancho!5e0!3m2!1ses!2sec!4v1534295140956" width="70%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </center>
 </section>

    <!--==========================
      Clients Section
    ============================-->
    <!-- <section id="testimonials" class="section-bg wow fadeInUp">
      <div class="container">

        <header class="section-header">
          <h3>Testimonios</h3>
        </header>

        <div class="owl-carousel testimonials-carousel">

          <div class="testimonial-item">
            <img src="img/testimonial-1.jpg" class="testimonial-img" alt="">
            <h3>Saul Goodman</h3>
            <h4>Ceo &amp; Founder</h4>
            <p>
              <img src="img/quote-sign-left.png" class="quote-sign-left" alt="">
              Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
              <img src="img/quote-sign-right.png" class="quote-sign-right" alt="">
            </p>
          </div>

          <div class="testimonial-item">
            <img src="img/testimonial-2.jpg" class="testimonial-img" alt="">
            <h3>Sara Wilsson</h3>
            <h4>Designer</h4>
            <p>
              <img src="img/quote-sign-left.png" class="quote-sign-left" alt="">
              Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
              <img src="img/quote-sign-right.png" class="quote-sign-right" alt="">
            </p>
          </div>

          <div class="testimonial-item">
            <img src="img/testimonial-3.jpg" class="testimonial-img" alt="">
            <h3>Jena Karlis</h3>
            <h4>Store Owner</h4>
            <p>
              <img src="img/quote-sign-left.png" class="quote-sign-left" alt="">
              Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
              <img src="img/quote-sign-right.png" class="quote-sign-right" alt="">
            </p>
          </div>

          <div class="testimonial-item">
            <img src="img/testimonial-4.jpg" class="testimonial-img" alt="">
            <h3>Matt Brandon</h3>
            <h4>Freelancer</h4>
            <p>
              <img src="img/quote-sign-left.png" class="quote-sign-left" alt="">
              Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
              <img src="img/quote-sign-right.png" class="quote-sign-right" alt="">
            </p>
          </div>

          <div class="testimonial-item">
            <img src="img/testimonial-5.jpg" class="testimonial-img" alt="">
            <h3>John Larson</h3>
            <h4>Entrepreneur</h4>
            <p>
              <img src="img/quote-sign-left.png" class="quote-sign-left" alt="">
              Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
              <img src="img/quote-sign-right.png" class="quote-sign-right" alt="">
            </p>
          </div>

        </div>

      </div>
    </section> --><!-- #testimonials -->

    <!--==========================
      Team Section
    ============================-->
    <!-- <section id="team">
      <div class="container">
        <div class="section-header wow fadeInUp">
          <h3>Team</h3>
          <p>...</p>
        </div>

        <div class="row">

          <div class="col-lg-3 col-md-6 wow fadeInUp">
            <div class="member">
              <img src="img/team-1.jpg" class="img-fluid" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Walter White</h4>
                  <span>Chief Executive Officer</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="member">
              <img src="img/team-2.jpg" class="img-fluid" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Sarah Jhonson</h4>
                  <span>Product Manager</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
            <div class="member">
              <img src="img/team-3.jpg" class="img-fluid" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>William Anderson</h4>
                  <span>CTO</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="member">
              <img src="img/team-4.jpg" class="img-fluid" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Amanda Jepson</h4>
                  <span>Accountant</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section> --><!-- #team -->

    <!--==========================
      Contact Section
    ============================-->
     <section id="contact" class="section-bg wow fadeInUp">
      <div class="container">

        <div class="section-header">
          <h3>Contactanos</h3>
          <p>....</p>
        </div>

        <div class="row contact-info">

          <div class="col-md-4">
            <div class="contact-address">
              <i class="ion-ios-location-outline"></i>
              <h3>Dirección</h3>
              <address><?php echo $this->informacion["direccion"]; ?></address>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-phone">
              <i class="ion-ios-telephone-outline"></i>
              <h3>Telefono</h3>
              <p><a href="tel:+593992573097"><?php echo $this->informacion["telefono"]; ?></a></p>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-email">
              <i class="ion-ios-email-outline"></i>
              <h3>Correo</h3>
              <p><a href="mailto:info@example.com"><?php echo $this->informacion["correo"]; ?></a></p>
            </div>
          </div>

        </div>

        <div class="form">
          <div id="sendmessage">Tu mensaje ha sido enviado. Gracias!</div>
          <div id="errormessage"></div>
    <form id="agregar"  action="">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombres" data-rule="minlen:4" data-msg="Su nombre debe tener al menos 4 letras" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Correo" data-rule="email" data-msg="Por favor, coloque un correo valido" />
                <div class="validation"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="asunto" id="asunto" placeholder="Asunto" data-rule="minlen:4" data-msg="El asunto debe tener al menos 8 letras" />
              <div class="validation"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="mensaje" id="mensaje" rows="5" data-rule="required" data-msg="Por favor, escriba el mensaje que desea enviarnos." placeholder="Mensaje"></textarea>
              <div class="validation"></div>
            </div>
            <div class="text-center"><button type="button" id="enviar_email">Enviar Mensaje</button></div>
          </form>
        </div>

      </div>
    </section><!-- #contact -->

  </main>